export const START_SIGNUP = 'SIGNUP_STARTS';
export const SUCCESSFUL_SIGNUP = 'SIGNUP_COMPLETE';
export const FAILED_SIGNUP = 'SIGNUP_ERROR';
export const START_SIGNIN = 'SIGNIN_STARTS';
export const SUCCESSFUL_SIGNIN = 'SIGNIN_COMPLETE';
export const FAILED_SIGNIN = 'SIGNIN_ERROR';

export const START_GET_USER_DOCUMENT = 'GET_USER_DOCUMENT_STARTS';
export const SUCCESS_GET_USER_DOCUMENT = 'GET_USER_DOCUMENT_COMPLETE';
export const ERROR_GET_USER_DOCUMENT = 'GET_USER_DOCUMENT_ERROR';

export const START_CREATING_DOCUMENT = 'CREATE_USER_DOCUMENT_STARTS';
export const DONE_CREATING_DOCUMENT = 'CREATE_USER_DOCUMENT_COMPLETE';
export const ERROR_CREATING_DOCUMENT = 'CREATE_USER_DOCUMENT_ERROR';

export const START_FETCHING_PUBLIC_DOCUMENTS = 'FETCH_PUBLIC_DOCUMENT_STARTS';

export const START_FETCHING_ROLE_DOCUMENTS = 'FETCH_ROLE_DOCUMENT_STARTS';
