export const START_SIGNUP = 'SIGNUP_STARTS';
export const SUCCESSFUL_SIGNUP = 'SIGNUP_COMPLETE';
export const FAILED_SIGNUP = 'SIGNUP_ERROR';

export const START_SIGNIN = 'SIGNIN_STARTS';
export const SUCCESSFUL_SIGNIN = 'SIGNIN_COMPLETE';
export const FAILED_SIGNIN = 'SIGNIN_ERROR';

export const START_GET_USER_DOCUMENT = 'GET_USER_DOCUMENT_STARTS';
export const SUCCESS_GET_USER_DOCUMENT = 'GET_USER_DOCUMENT_COMPLETE';
export const ERROR_GET_USER_DOCUMENT = 'GET_USER_DOCUMENT_ERROR';

export const START_CREATING_DOCUMENT = 'CREATE_USER_DOCUMENT_STARTS';
export const DONE_CREATING_DOCUMENT = 'CREATE_USER_DOCUMENT_COMPLETE';
export const ERROR_CREATING_DOCUMENT = 'CREATE_USER_DOCUMENT_ERROR';

export const START_FETCHING_PUBLIC_DOCUMENTS = 'FETCH_PUBLIC_DOCUMENT_STARTS';
export const DONE_FETCHING_PUBLIC_DOCUMENTS = 'FETCH_PUBLIC_DOCUMENT_COMPLETE';
export const ERROR_FETCHING_PUBLIC_DOCUMENTS = 'FETCH_PUBLIC_DOCUMENT_ERROR';

export const START_FETCHING_ROLE_DOCUMENTS = 'FETCH_ROLE_DOCUMENT_STARTS';
export const DONE_FETCHING_ROLE_DOCUMENTS = 'FETCH_ROLE_DOCUMENT_COMPLETE';
export const ERROR_FETCHING_ROLE_DOCUMENTS = 'FETCH_ROLE_DOCUMENT_ERROR';

export const START_FETCHING_ALL_DOCUMENTS = 'FETCH_ALL_DOCUMENT_STARTS';
export const DONE_FETCHING_ALL_DOCUMENTS = 'FETCH_ALL_DOCUMENTS_COMPLETE';
export const ERROR_FETCHING_ALL_DOCUMENTS = 'FETCH_ALL_DOCUMENTS_ERROR';

export const SET_USER_ROLE = 'SET_USER_ROLETYPE';

export const START_READING_DOCUMENT = 'START_READING_DOCUMENT';
export const DONE_READING_DOCUMENT = 'DONE_READING_DOCUMENT';
export const ERROR_READING_DOCUMENT = 'ERROR_READING_DOCUMENT';

export const START_DELETING_DOCUMENT = 'START_DELETING_DOCUMENT';
export const DONE_DELETING_DOCUMENT = 'DONE_DELETING_DOCUMENT';
export const ERROR_DELETING_DOCUMENT = 'ERROR_DELETING_DOCUMENT';

export const START_GETTING_ALL_USERS = 'START_GETTING_ALL_USERS';
export const ERROR_GETTING_ALL_USERS = 'ERROR_GETTING_ALL_USERS';
export const FINISH_GETTING_ALL_USERS = 'FINISH_GETTING_ALL_USERS';

export const START_UPDATING_USER = 'START_UPDATING_USER';
export const DONE_UPDATING_USER = 'DONE_UPDATING_USER';
export const ERROR_UPDATING_USER = 'ERROR_UPDATING_USER';

export const UPDATE_EMAIL = 'UPDATE_EMAIL';

export const ERROR_SEARCHING_DOCUMENTS = 'ERROR_SEARCHING_DOCUMENTS';
export const DONE_SEARCHING_DOCUMENTS = 'DONE_SEARCHING_DOCUMENTS';

export const DONE_DEACTIVATING_USER = 'DONE_DEACTIVATING_USER';
export const ERROR_DEACTIVATING_USER = 'ERROR_DEACTIVATING_USER';

export const USER_SIGNOUT = 'USER_SIGNOUT';
